### ISSUE TITLE
Feature Request: upload to a temp folder and move it when it's done.

### ISSUE THREAD

**Issue by ivands** [gilmarsquinelato/serverless-spa#6]
I've been thinking about how we can improve deployment downtime when deploying a new version to S3.
Right now your SPA site will stop working when the site is uploading.
This is an issue when your site becomes bigger.
S3 can get pretty slow at uploading the files.
So I was wondering if it would be possible to upload to a temporary folder.
And when the upload process is completed we move the folder to its destination.
This would probably fix the downtime issue.

Any suggestions?

**Comment by gilmarsquinelato** [comment]
I've not tested it with a bigger site, but I think that this would be an issue with AWS S3 itself.
Maybe a gzip can drastically reduce the size of the site, and S3 have support to it.
In one of my projects, the gzip reduced the bundle from 2Mb to 500Kb.
