### ISSUE TITLE
Brotli support

### ISSUE THREAD

**Issue by pfulop** [gilmarsquinelato/serverless-spa#9]
Currently, if I decide to compress my files using brotli compression plugin for webpack the files can't be transferred to s3. This is due to the fact that the mime-types library which uses mime-db doesn't have Brotli mime-type in their database, returns false and s3 upload crashes. 

I would like to be able to serve *.br files to users since the difference in file size after compression is huge. The solution would be either 

- to try and add it to the mime-type database which I am not sure if it's possible since they usually need some official documentation on the mime-type and all I can find are issues in google repo
- or make a condition in this lib to set the content type to brotli whenever there is *.br file.

I just wanted to ask first before opening any PR.

**Comment by gilmarsquinelato** [comment]
Hello!
Any improvements are wellcome.
If possibile could you send a PR with this feature?

**Comment by pfulop** [comment]
Never mind, I did more research on this and it's not mime-type but rather content-encoding. I just need to make sure my files don't end with br extension. Thanks a lot for this library tho.
